FROM alpine:3

LABEL author="Achmad Rahman Mawardi"
LABEL company="achmad rahman company" website="https://achmadrahmanm.github.io"

RUN mkdir hello
RUN echo "Hello, World!" > "hello/world.txt"

CMD cat "hello/world.txt"